### PR TITLE
Bugfix s3 upload

### PR DESCRIPTION
**Pull request by glance-**
Bugfix and restructure some code so ckanclient can be used to upload data-files to s3.

### CODE REVIEW

**Comment by metaodi** [comment]
For me this PR works perfectly :+1: . Would be great if it gets merged soon :wink:

**Comment by amercader** [comment]
@rgrp You are probably the one with more experience to check this

**Comment by rufuspollock** [comment]
@glance- if you had any additional tests for this it would be great but we'll merge this right now (sorry for the delay!)

**Comment by glance-** [comment]
Thanks for merging this fixes.

Nope, i didn't write any integration/unittests, i just tested it against a real installation.

All the patches are quite trivial, and quite well broken down so they should be quite easy to review to see that they are doing the right ting<tm>.

I'm currently off to working on other non-ckan projects, but ill try to remember to revisit this one when/if i end up doing some more ckan-work.

**Comment by glance-** [comment]
This never got merged? or did it get force-pushed out of repo?

**Comment by rufuspollock** [comment]
Hmmm, i thought it got merged but somehow it seems not to. Any way you can resubmit - sorry about this!

**Pull request closed without merging**
