### PR TITLE
[deb]: Debian unstable source package added

### PR DESCRIPTION
**Pull request by fontanon**
I'm in the process of getting into debian unstable ckanclient and dpm.
I've created a branch for the debian source package on my ckanclient fork. This way the packaging issues could be developed separately. That's what i'm requesting to pull here.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@fontanon would it make sense to have the Deb stuff in dedicated 'debian-{version}' branch rather than in master?

PS: would you be interested in helping us package CKAN for Debian?

**Comment by fontanon** [comment]
@rgrp Ups! That was my intention. Sorry for requesting to pull on master. A dedicated 'debian-{version}' branch is the right way.

As for the CKAN packaging, I now some work has been done. Yes I'm interested, do you find more convenient to discuss it on CKAN-dev mailing list?

**Comment by rufuspollock** [comment]
Yes, let's discuss on ckan-dev re CKAN main package. Closing now and awaiting new pull.

**Comment by fontanon** [comment]
I'm afraid I can request to pull on a non-existent branch at okfn/ckanclient, would someone be so nice to create the branch before I request to pull there?

**Comment by rufuspollock** [comment]
@fontanon Created debian-sid branch here: https://github.com/okfn/ckanclient/tree/debian-sid :-)

**Comment by fontanon** [comment]
Done! Thanks @rgrp !

**Pull request closed without merging**
