### PR TITLE
CSV exporter for CKAN which runs as a rest client.

### PR DESCRIPTION
**Pull request by pudo**
This will translate each resource into a row that also has dataset metadata. If a dataset has no resources, a single row is created anyway.

### CODE REVIEW

**Comment by davidread** [comment]
Nice script! I'm not sure we want utils like this to live in the ckanclient repo though. We used to have ckanext for this sort of thing. I've got a bunch of scripts in ckan/bin. How about we create ckan-scripts for this sort of thing?

**Comment by pudo** [comment]
+1 thats why i made it a pull request, should have mentioned. I have quite a lot of scripts lying around that could use a home. Can you perhaps kick it off with yours and I'll join in?

**Comment by rufuspollock** [comment]
I think putting this into ckanclient is a problem. Put them in contrib or utils directory :-)

**Comment by davidread** [comment]
I've put the script in the contrib directory as requested:

https://github.com/okfn/ckanclient/commit/eeb0df8bccfb249cb30e42ed436197a6db249c00

**Pull request closed without merging**
