### PR TITLE
Support non-ascii file upload with ckanclient

### PR DESCRIPTION
**Pull request by Hoedic**
Currently, ckanclient throws errors when trying to upload non-ascii file (mainly with latin1 encoding).
This code proposes some changes to support any time of encoding as it does not "opening" the files to be uploaded.
Also adds some exception management at the file upload level.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@davidread would you be up for a review?

**Comment by davidread** [comment]
Looks like much simpler code using the pycurl library and more error handling, which is v. good. However I've not tried it and this part of ckanclient which although I've looked at previously, I've failed to understand - the ins and outs of multipart form encoding seem pretty obscure.

@slmnhq wrote the original code 57e86c33b , so perhaps he can comment on this change?

**Comment by slmnhq** [comment]
+1 for pycurl or requests.

 I was trying to avoid introducing a new dependency beyond httplib.

**Comment by Hoedic** [comment]
I initially tried to improve the existing code without any news dependency but it appeared to be difficult to do (Note: I am far from an experienced developer). As a result, pycurl seemed to be a reasonable requirement given the task at end.

**Comment by rufuspollock** [comment]
No problem introducing a dep in my opinion but i'm wondering if http://www.python-requests.org/en/latest/ might not be better than pycurl as it would be pure python ...

**Comment by rsignell-usgs** [comment]
+1 for requests

**Comment by rufuspollock** [comment]
@Hoedic i know itis a bit of an ask but would you consider a switch for your patch to use requests - you'll probably like it even more :-)

**Comment by Hoedic** [comment]
Yes, I'll look at that. Let me few days because I have a rush for the moment

**Comment by rufuspollock** [comment]
@Hoedic so what i'm going to suggest is we merge your PR now (its a definite improvement) and then we try to refactor to use requests - i've opened an issue for this as #31

**Pull request merged**
